### ISSUE TITLE
Select and use "word packs" rather than submitting words

### ISSUE THREAD

**Issue by skyebs** [SMaxOwok/ui-pictionary#33]
Maybe rather than submitting words, players could select word packs to play from? seems like a lot of folks get stressed out trying to pick words and lot of stuff gets reused from previous games. so rather than picking words people could vote for word packs? we could also label them with difficulty and make words from certain packs worth more?

**Comment by SMaxOwok** [comment]
I'm on the fence for this one.  I think my instinct would be to see how we can encourage players to submit more words.  Maybe as a start increasing the timer from 30s to 60s.

**Comment by SMaxOwok** [comment]
Going to close this for now.  Let's start with the increased pre-game timer to see if we can get more word submitted first.  Tracked in #44
